name: nimble_flutter_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  dio: ^4.0.0
  freezed_annotation: ^2.0.0
  json_annotation: ^4.8.1
  go_router: ^6.0.0
  riverpod_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.0.0
  freezed: ^2.0.0
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pharmaciesList.json
    - assets/medicationsList.txt
